/* Generated by re2c 0.13.5 on Tue Jun 26 15:11:18 2012 */
// -*- c++ -*-

// re2c --case-insensitive -i -o lex.cc lex.re

#ifndef CURRENTIA_QUERY_LEXER_H_
#define CURRENTIA_QUERY_LEXER_H_

#include <list>
#include <iostream>
#include <algorithm>
#include <functional>
#include <sstream>

#include <ctype.h>
#include <string.h>

#include "currentia/trait/non-copyable.h"



#define log(str) std::cout << str << std::endl
#define dump(x) std::cout << #x << " => [" << (x) << "]" << std::endl

namespace currentia {
#define CURRENTIA_DEFINE_ENUM(TOKEN, AS_STRING) \
    TOKEN,

#define CURRENTIA_DEFINE_SWITCH_STRING(TOKEN, AS_STRING)        \
    case TOKEN: return AS_STRING;

#define CURRENTIA_DEFINE_TOKEN_LIST(DEFINE)                     \
    DEFINE(TOKEN_SELECT, "SELECT")                              \
    DEFINE(TOKEN_FROM, "FROM")                                  \
    DEFINE(TOKEN_WHERE, "WHERE")                                \
    /* conjunctives */                                          \
    DEFINE(TOKEN_AND, "AND")                                    \
    DEFINE(TOKEN_OR, "OR")                                      \
    /* }}} DML -------------------------------- */              \
                                                                \
    /* {{{ DDL -------------------------------- */              \
    DEFINE(TOKEN_CREATE, "CREATE")                              \
    DEFINE(TOKEN_STREAM, "STREAM")                              \
    DEFINE(TOKEN_TABLE, "TABLE")                                \
    /* }}} DDL -------------------------------- */              \
                                                                \
    /* identifier */                                            \
    DEFINE(TOKEN_NAME, "NAME")                                  \
                                                                \
    /* string */                                                \
    DEFINE(TOKEN_STRING, "STRING")                              \
                                                                \
    /* numbers */                                               \
    DEFINE(TOKEN_INTEGER, "INTEGER")                            \
    DEFINE(TOKEN_FLOAT, "FLOAT")                                \
                                                                \
    /* misc */                                                  \
    DEFINE(TOKEN_NOT, "NOT")                                    \
    DEFINE(TOKEN_IN, "IN")                                      \
                                                                \
    /* window specification */                                  \
    DEFINE(TOKEN_ROWS, "ROWS")                                  \
    DEFINE(TOKEN_MSEC, "MSEC")                                  \
    DEFINE(TOKEN_SEC, "SEC")                                    \
    DEFINE(TOKEN_MIN, "MIN")                                    \
    DEFINE(TOKEN_HOUR, "HOUR")                                  \
    DEFINE(TOKEN_DAY, "DAY")                                    \
    DEFINE(TOKEN_ADVANCE, "ADVANCE")                            \
    DEFINE(TOKEN_LBRACKET, "LBRACKET")                          \
    DEFINE(TOKEN_RBRACKET, "RBRACKET")                          \
                                                                \
    /* other symbols */                                         \
    DEFINE(TOKEN_COMMA, "COMMA")                                \
    DEFINE(TOKEN_DOT, "DOT")                                    \
    DEFINE(TOKEN_LPAREN, "LPAREN")                              \
    DEFINE(TOKEN_RPAREN, "RPAREN")                              \
                                                                \
    /* comparator */                                            \
    DEFINE(TOKEN_EQUAL, "EQUAL")                                \
    DEFINE(TOKEN_NOT_EQUAL, "NOT_EQUAL")                        \
    DEFINE(TOKEN_LESS_THAN, "LESS_THAN")                        \
    DEFINE(TOKEN_LESS_THAN_EQUAL, "LESS_THAN_EQUAL")            \
    DEFINE(TOKEN_GREATER_THAN, "GREATER_THAN")                  \
    DEFINE(TOKEN_GREATER_THAN_EQUAL, "GREATER_THAN_EQUAL")      \
                                                                \
    /* error */                                                 \
    DEFINE(TOKEN_UNKNOWN, "UNKNOWN")                            \
    DEFINE(TOKEN_EOS, "EOS")

    class Lexer : private NonCopyable<Lexer> {
    private:
        std::istream* ifs_ptr_;

        char* buffer_;
        char* yy_cursor_;
        char* yy_marker_;
        char* yy_limit_;
        char* token_begin_;
        long buffer_size_;
        long line_number_;

    public:
        typedef Lexer* ptr_t;

        enum Token {
            CURRENTIA_DEFINE_TOKEN_LIST(CURRENTIA_DEFINE_ENUM)
        };

        static std::string token_to_string(enum Token token) {
            switch (token) {
                CURRENTIA_DEFINE_TOKEN_LIST(CURRENTIA_DEFINE_SWITCH_STRING)
            default:
                return "UNEXPECTED_TOKEN";
            };
        }

        Lexer(std::istream* ifs_ptr, long buffer_init_size = 1024):
            ifs_ptr_(ifs_ptr),
            buffer_size_(buffer_init_size),
            line_number_(1) {
            // Allocate
            buffer_ = reinterpret_cast<char*>(malloc(sizeof(char) * buffer_size_));
            // Init
            yy_cursor_ = yy_marker_ = yy_limit_ = token_begin_ = buffer_;
        }

        ~Lexer() {
            free(buffer_);
        }

        inline
        int get_buffer_used_size() {
            return yy_limit_ - buffer_;
        }

        inline
        int get_buffer_allocated_size() {
            return buffer_size_;
        }

        bool fill(int n) {
            if (ifs_ptr_->eof() && (yy_cursor_ >= yy_limit_))
                return false;   // EOS

            int remained_characters_count = yy_limit_ - yy_cursor_;
            int yy_cursor_offset = yy_cursor_ - buffer_;
            int yy_marker_offset = yy_marker_ - buffer_;
            int yy_limit_offset = yy_limit_ - buffer_;

            // dump(yy_cursor_offset);
            // dump(yy_limit_offset);

            if (remained_characters_count + n >= buffer_size_) {
                // Extend buffer
                log("We need to extend buffer");
                buffer_ = reinterpret_cast<char*>(realloc(buffer_, buffer_size_ *= 2));
                // Adjust position
                yy_cursor_ = token_begin_ = buffer_;
                yy_marker_ = buffer_ + yy_marker_offset;
                yy_limit_  = buffer_ + yy_limit_offset;
            } else if (remained_characters_count > 0) {
                // Shift remained characters in the buffer_ to head of the buffer_
                memmove(buffer_, yy_cursor_, sizeof(char) * remained_characters_count);
                // Adjust position (shift)
                yy_cursor_ = token_begin_ = buffer_;
                yy_marker_ = buffer_ + (yy_marker_offset - yy_cursor_offset);
                yy_limit_  = buffer_ + (yy_limit_offset - yy_cursor_offset);
            }

            // This line is very important (fill buffer with EOF)
            int empty_buffer_count = (buffer_ + buffer_size_) - yy_limit_;
            // dump(empty_buffer_count);
            // dump(buffer_);
            memset(yy_limit_, '\0', sizeof(char) * empty_buffer_count);
            // dump(buffer_);

            // Read characters from input stream
            ifs_ptr_->read(yy_limit_, empty_buffer_count);
            yy_limit_ += ifs_ptr_->gcount();
            // Dirty hack (for stringstream which doesn't give us a EOF character)
            if (ifs_ptr_->gcount() == 0 && *(yy_limit_ - 1) != '\0') {
                *(++yy_limit_) = '\0';
            }

            // log("Read");
            // dump(buffer_);

            return true;
        }

        std::string get_token_text() {
            return std::string(token_begin_, token_begin_ + get_token_length());
        }
        int get_token_length() {
            return yy_cursor_ - token_begin_;
        }

        enum Token get_next_token() {
        start:
            token_begin_ = yy_cursor_;

            
            {
                char yych;
                unsigned int yyaccept = 0;

                if ((yy_limit_ - yy_cursor_) < 8) if (!fill(8)) { return TOKEN_EOS; }
                yych = *yy_cursor_;
                switch (yych) {
                case 0x00:    goto yy47;
                case '\t':
                case '\v':
                case '\f':
                case ' ':    goto yy5;
                case '\n':    goto yy7;
                case '\r':    goto yy8;
                case '!':    goto yy42;
                case '"':    goto yy24;
                case '#':    goto yy3;
                case '(':    goto yy36;
                case ')':    goto yy38;
                case ',':    goto yy32;
                case '.':    goto yy34;
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    goto yy26;
                case '<':    goto yy43;
                case '=':    goto yy40;
                case '>':    goto yy45;
                case 'A':
                case 'a':    goto yy13;
                case 'B':
                case 'E':
                case 'G':
                case 'J':
                case 'K':
                case 'L':
                case 'P':
                case 'Q':
                case 'U':
                case 'V':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'b':
                case 'e':
                case 'g':
                case 'j':
                case 'k':
                case 'l':
                case 'p':
                case 'q':
                case 'u':
                case 'v':
                case 'x':
                case 'y':
                case 'z':    goto yy23;
                case 'C':
                case 'c':    goto yy15;
                case 'D':
                case 'd':    goto yy22;
                case 'F':
                case 'f':    goto yy11;
                case 'H':
                case 'h':    goto yy21;
                case 'I':
                case 'i':    goto yy18;
                case 'M':
                case 'm':    goto yy20;
                case 'N':
                case 'n':    goto yy17;
                case 'O':
                case 'o':    goto yy14;
                case 'R':
                case 'r':    goto yy19;
                case 'S':
                case 's':    goto yy9;
                case 'T':
                case 't':    goto yy16;
                case 'W':
                case 'w':    goto yy12;
                case '[':    goto yy28;
                case ']':    goto yy30;
                default:    goto yy49;
                }
yy2:
                { line_number_++; goto start; }
yy3:
                ++yy_cursor_;
                yych = *yy_cursor_;
                goto yy141;
yy4:
                { goto start; }
yy5:
                ++yy_cursor_;
                yych = *yy_cursor_;
                goto yy139;
yy6:
                { goto start; }
yy7:
                yych = *++yy_cursor_;
                goto yy2;
yy8:
                yych = *++yy_cursor_;
                goto yy2;
yy9:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case 'E':
                case 'e':    goto yy124;
                case 'T':
                case 't':    goto yy125;
                default:    goto yy68;
                }
yy10:
                { return TOKEN_NAME; }
yy11:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'R':
                case 'r':    goto yy120;
                default:    goto yy68;
                }
yy12:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'H':
                case 'h':    goto yy115;
                default:    goto yy68;
                }
yy13:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'D':
                case 'd':    goto yy105;
                case 'N':
                case 'n':    goto yy106;
                default:    goto yy68;
                }
yy14:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'R':
                case 'r':    goto yy103;
                default:    goto yy68;
                }
yy15:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'R':
                case 'r':    goto yy97;
                default:    goto yy68;
                }
yy16:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'A':
                case 'a':    goto yy92;
                default:    goto yy68;
                }
yy17:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'O':
                case 'o':    goto yy89;
                default:    goto yy68;
                }
yy18:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'N':
                case 'n':    goto yy87;
                default:    goto yy68;
                }
yy19:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'O':
                case 'o':    goto yy83;
                default:    goto yy68;
                }
yy20:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'I':
                case 'i':    goto yy76;
                case 'S':
                case 's':    goto yy77;
                default:    goto yy68;
                }
yy21:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'O':
                case 'o':    goto yy72;
                default:    goto yy68;
                }
yy22:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'A':
                case 'a':    goto yy69;
                default:    goto yy68;
                }
yy23:
                yych = *++yy_cursor_;
                goto yy68;
yy24:
                yyaccept = 0;
                yych = *(yy_marker_ = ++yy_cursor_);
                switch (yych) {
                case '"':    goto yy61;
                case '.':
                case '[':
                case ']':
                case '^':
                case '|':    goto yy64;
                default:    goto yy25;
                }
yy25:
                { return TOKEN_UNKNOWN; }
yy26:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '.':    goto yy58;
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    goto yy56;
                default:    goto yy27;
                }
yy27:
                { return TOKEN_INTEGER; }
yy28:
                ++yy_cursor_;
                { return TOKEN_LBRACKET; }
yy30:
                ++yy_cursor_;
                { return TOKEN_RBRACKET; }
yy32:
                ++yy_cursor_;
                { return TOKEN_COMMA; }
yy34:
                ++yy_cursor_;
                { return TOKEN_DOT; }
yy36:
                ++yy_cursor_;
                { return TOKEN_LPAREN; }
yy38:
                ++yy_cursor_;
                { return TOKEN_RPAREN; }
yy40:
                ++yy_cursor_;
                { return TOKEN_EQUAL; }
yy42:
                yych = *++yy_cursor_;
                switch (yych) {
                case '=':    goto yy54;
                default:    goto yy25;
                }
yy43:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '=':    goto yy52;
                default:    goto yy44;
                }
yy44:
                { return TOKEN_LESS_THAN; }
yy45:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '=':    goto yy50;
                default:    goto yy46;
                }
yy46:
                { return TOKEN_GREATER_THAN; }
yy47:
                ++yy_cursor_;
                { return TOKEN_EOS; }
yy49:
                yych = *++yy_cursor_;
                goto yy25;
yy50:
                ++yy_cursor_;
                { return TOKEN_GREATER_THAN_EQUAL; }
yy52:
                ++yy_cursor_;
                { return TOKEN_LESS_THAN_EQUAL; }
yy54:
                ++yy_cursor_;
                { return TOKEN_NOT_EQUAL; }
yy56:
                ++yy_cursor_;
                if (yy_limit_ <= yy_cursor_) if (!fill(1)) { return TOKEN_EOS; }
                yych = *yy_cursor_;
                switch (yych) {
                case '.':    goto yy58;
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    goto yy56;
                default:    goto yy27;
                }
yy58:
                ++yy_cursor_;
                if (yy_limit_ <= yy_cursor_) if (!fill(1)) { return TOKEN_EOS; }
                yych = *yy_cursor_;
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':    goto yy58;
                default:    goto yy60;
                }
yy60:
                { return TOKEN_FLOAT; }
yy61:
                yyaccept = 1;
                yy_marker_ = ++yy_cursor_;
                if (yy_limit_ <= yy_cursor_) if (!fill(1)) { return TOKEN_EOS; }
                yych = *yy_cursor_;
                switch (yych) {
                case '"':    goto yy61;
                case '.':
                case '[':
                case ']':
                case '^':
                case '|':    goto yy64;
                default:    goto yy63;
                }
yy63:
                { return TOKEN_STRING; }
yy64:
                ++yy_cursor_;
                if (yy_limit_ <= yy_cursor_) if (!fill(1)) { return TOKEN_EOS; }
                yych = *yy_cursor_;
                switch (yych) {
                case '"':    goto yy61;
                case '.':
                case '[':
                case ']':
                case '^':
                case '|':    goto yy64;
                default:    goto yy66;
                }
yy66:
                yy_cursor_ = yy_marker_;
                switch (yyaccept) {
                case 0: 	goto yy25;
                case 1: 	goto yy63;
                }
yy67:
                ++yy_cursor_;
                if (yy_limit_ <= yy_cursor_) if (!fill(1)) { return TOKEN_EOS; }
                yych = *yy_cursor_;
yy68:
                switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy10;
                }
yy69:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'Y':
                case 'y':    goto yy70;
                default:    goto yy68;
                }
yy70:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy71;
                }
yy71:
                { return TOKEN_DAY; }
yy72:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'U':
                case 'u':    goto yy73;
                default:    goto yy68;
                }
yy73:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'R':
                case 'r':    goto yy74;
                default:    goto yy68;
                }
yy74:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy75;
                }
yy75:
                { return TOKEN_HOUR; }
yy76:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'N':
                case 'n':    goto yy81;
                default:    goto yy68;
                }
yy77:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'E':
                case 'e':    goto yy78;
                default:    goto yy68;
                }
yy78:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'C':
                case 'c':    goto yy79;
                default:    goto yy68;
                }
yy79:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy80;
                }
yy80:
                { return TOKEN_MSEC; }
yy81:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy82;
                }
yy82:
                { return TOKEN_MIN; }
yy83:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'W':
                case 'w':    goto yy84;
                default:    goto yy68;
                }
yy84:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'S':
                case 's':    goto yy85;
                default:    goto yy68;
                }
yy85:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy86;
                }
yy86:
                { return TOKEN_ROWS; }
yy87:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy88;
                }
yy88:
                { return TOKEN_IN; }
yy89:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'T':
                case 't':    goto yy90;
                default:    goto yy68;
                }
yy90:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy91;
                }
yy91:
                { return TOKEN_NOT; }
yy92:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'B':
                case 'b':    goto yy93;
                default:    goto yy68;
                }
yy93:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'L':
                case 'l':    goto yy94;
                default:    goto yy68;
                }
yy94:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'E':
                case 'e':    goto yy95;
                default:    goto yy68;
                }
yy95:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy96;
                }
yy96:
                { return TOKEN_TABLE; }
yy97:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'E':
                case 'e':    goto yy98;
                default:    goto yy68;
                }
yy98:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'A':
                case 'a':    goto yy99;
                default:    goto yy68;
                }
yy99:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'T':
                case 't':    goto yy100;
                default:    goto yy68;
                }
yy100:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'E':
                case 'e':    goto yy101;
                default:    goto yy68;
                }
yy101:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy102;
                }
yy102:
                { return TOKEN_CREATE; }
yy103:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy104;
                }
yy104:
                { return TOKEN_OR; }
yy105:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'V':
                case 'v':    goto yy109;
                default:    goto yy68;
                }
yy106:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'D':
                case 'd':    goto yy107;
                default:    goto yy68;
                }
yy107:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy108;
                }
yy108:
                { return TOKEN_AND; }
yy109:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'A':
                case 'a':    goto yy110;
                default:    goto yy68;
                }
yy110:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'N':
                case 'n':    goto yy111;
                default:    goto yy68;
                }
yy111:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'C':
                case 'c':    goto yy112;
                default:    goto yy68;
                }
yy112:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'E':
                case 'e':    goto yy113;
                default:    goto yy68;
                }
yy113:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy114;
                }
yy114:
                { return TOKEN_ADVANCE; }
yy115:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'E':
                case 'e':    goto yy116;
                default:    goto yy68;
                }
yy116:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'R':
                case 'r':    goto yy117;
                default:    goto yy68;
                }
yy117:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'E':
                case 'e':    goto yy118;
                default:    goto yy68;
                }
yy118:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy119;
                }
yy119:
                { return TOKEN_WHERE; }
yy120:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'O':
                case 'o':    goto yy121;
                default:    goto yy68;
                }
yy121:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'M':
                case 'm':    goto yy122;
                default:    goto yy68;
                }
yy122:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy123;
                }
yy123:
                { return TOKEN_FROM; }
yy124:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'C':
                case 'c':    goto yy132;
                case 'L':
                case 'l':    goto yy131;
                default:    goto yy68;
                }
yy125:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'R':
                case 'r':    goto yy126;
                default:    goto yy68;
                }
yy126:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'E':
                case 'e':    goto yy127;
                default:    goto yy68;
                }
yy127:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'A':
                case 'a':    goto yy128;
                default:    goto yy68;
                }
yy128:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'M':
                case 'm':    goto yy129;
                default:    goto yy68;
                }
yy129:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy130;
                }
yy130:
                { return TOKEN_STREAM; }
yy131:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'E':
                case 'e':    goto yy134;
                default:    goto yy68;
                }
yy132:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy133;
                }
yy133:
                { return TOKEN_SEC; }
yy134:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'C':
                case 'c':    goto yy135;
                default:    goto yy68;
                }
yy135:
                yych = *++yy_cursor_;
                switch (yych) {
                case 'T':
                case 't':    goto yy136;
                default:    goto yy68;
                }
yy136:
                ++yy_cursor_;
                switch ((yych = *yy_cursor_)) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':    goto yy67;
                default:    goto yy137;
                }
yy137:
                { return TOKEN_SELECT; }
yy138:
                ++yy_cursor_;
                if (yy_limit_ <= yy_cursor_) if (!fill(1)) { return TOKEN_EOS; }
                yych = *yy_cursor_;
yy139:
                switch (yych) {
                case '\t':
                case '\v':
                case '\f':
                case ' ':    goto yy138;
                default:    goto yy6;
                }
yy140:
                ++yy_cursor_;
                if (yy_limit_ <= yy_cursor_) if (!fill(1)) { return TOKEN_EOS; }
                yych = *yy_cursor_;
yy141:
                switch (yych) {
                case '\n':    goto yy142;
                default:    goto yy140;
                }
yy142:
                ++yy_cursor_;
                yych = *yy_cursor_;
                goto yy4;
            }

        }

        static bool is_token_conjunctive(Token token) {
            return token == TOKEN_AND || token == TOKEN_OR;
        }

        static bool is_token_value(Token token) {
            return token == TOKEN_STRING || token == TOKEN_INTEGER || token == TOKEN_FLOAT;
        }

        long get_current_line_number() {
            return line_number_;
        }

        long get_current_cursor_point() {
            return 0;
        }

        template <typename Stream>
        void print_error_point(Stream& stream = std::cout) {
            // stream << current_line_ << std::endl;
            // for (int i = 0; i < get_current_cursor_point() - 1; ++i)
            //     stream << '_';
            // stream << '^';
        }
    };

#undef CURRENTIA_DEFINE_ENUM
#undef CURRENTIA_DEFINE_SWITCH_STRING
#undef CURRENTIA_DEFINE_TOKEN_LIST
}

#ifdef CURRENTIA_IS_LEXER_MAIN_
int main(int argc, char** argv)
{
    std::istringstream is("abc def ghi");
    currentia::Lexer lexer(&is);
    currentia::Lexer::Token token;

    while ((token = lexer.get_next_token()) != currentia::Lexer::TOKEN_EOS) {
        std::cout << "token => " << currentia::Lexer::token_to_string(token)
                  << " '" << lexer.get_token_text() << "'" << std::endl;
    }

    return 0;
}
#endif

#endif  /* ! CURRENTIA_QUERY_LEXER_H_  */
