#define TOKEN_UNKNOWN                         1
#define TOKEN_RELATION                        2
#define TOKEN_NAME                            3
#define TOKEN_LPAREN                          4
#define TOKEN_RPAREN                          5
#define TOKEN_STREAM                          6
#define TOKEN_FROM                            7
#define TOKEN_LBRACE                          8
#define TOKEN_RBRACE                          9
#define TOKEN_COMMA                          10
#define TOKEN_WHERE                          11
#define TOKEN_SELECT                         12
#define TOKEN_PROJECT                        13
#define TOKEN_MEAN                           14
#define TOKEN_SUM                            15
#define TOKEN_ELECT                          16
#define TOKEN_COMBINE                        17
#define TOKEN_LBRACKET                       18
#define TOKEN_RBRACKET                       19
#define TOKEN_RECENT                         20
#define TOKEN_SLIDE                          21
#define TOKEN_ROWS                           22
#define TOKEN_MSEC                           23
#define TOKEN_SEC                            24
#define TOKEN_MIN                            25
#define TOKEN_HOUR                           26
#define TOKEN_DAY                            27
#define TOKEN_DOT                            28
#define TOKEN_AND                            29
#define TOKEN_OR                             30
#define TOKEN_NOT                            31
#define TOKEN_EQUAL                          32
#define TOKEN_NOT_EQUAL                      33
#define TOKEN_LESS_THAN                      34
#define TOKEN_LESS_THAN_EQUAL                35
#define TOKEN_GREATER_THAN                   36
#define TOKEN_GREATER_THAN_EQUAL             37
#define TOKEN_COLON                          38
#define TOKEN_TYPE_INT                       39
#define TOKEN_TYPE_FLOAT                     40
#define TOKEN_TYPE_STRING                    41
#define TOKEN_TYPE_BLOB                      42
#define TOKEN_STRING                         43
#define TOKEN_INTEGER                        44
#define TOKEN_FLOAT                          45
#define TOKEN_BLOB                           46
