#define TOKEN_EOS                             1
#define TOKEN_UNKNOWN                         2
#define TOKEN_RELATION                        3
#define TOKEN_LPAREN                          4
#define TOKEN_RPAREN                          5
#define TOKEN_STREAM                          6
#define TOKEN_LBRACE                          7
#define TOKEN_RBRACE                          8
#define TOKEN_COMMA                           9
#define TOKEN_NAME                           10
#define TOKEN_COLON                          11
#define TOKEN_TYPE_INT                       12
#define TOKEN_TYPE_FLOAT                     13
#define TOKEN_TYPE_STRING                    14
#define TOKEN_TYPE_BLOB                      15
#define TOKEN_SELECT                         16
#define TOKEN_PROJECT                        17
#define TOKEN_MEAN                           18
#define TOKEN_SUM                            19
#define TOKEN_ELECT                          20
#define TOKEN_JOIN                           21
#define TOKEN_WITH                           22
#define TOKEN_WHERE                          23
#define TOKEN_WIDTH                          24
#define TOKEN_SLIDE                          25
#define TOKEN_INTEGER                        26
#define TOKEN_FLOAT                          27
#define TOKEN_ROWS                           28
#define TOKEN_MSEC                           29
#define TOKEN_SEC                            30
#define TOKEN_MIN                            31
#define TOKEN_HOUR                           32
#define TOKEN_DAY                            33
#define TOKEN_DOT                            34
#define TOKEN_NOT                            35
#define TOKEN_STRING                         36
#define TOKEN_BLOB                           37
#define TOKEN_AND                            38
#define TOKEN_OR                             39
#define TOKEN_EQUAL                          40
#define TOKEN_NOT_EQUAL                      41
#define TOKEN_LESS_THAN                      42
#define TOKEN_LESS_THAN_EQUAL                43
#define TOKEN_GREATER_THAN                   44
#define TOKEN_GREATER_THAN_EQUAL             45
