#define TOKEN_UNKNOWN                         1
#define TOKEN_RELATION                        2
#define TOKEN_NAME                            3
#define TOKEN_LPAREN                          4
#define TOKEN_RPAREN                          5
#define TOKEN_STREAM                          6
#define TOKEN_FROM                            7
#define TOKEN_LBRACE                          8
#define TOKEN_RBRACE                          9
#define TOKEN_COMMA                          10
#define TOKEN_LBRACKET                       11
#define TOKEN_RBRACKET                       12
#define TOKEN_COLON                          13
#define TOKEN_TYPE_INT                       14
#define TOKEN_TYPE_FLOAT                     15
#define TOKEN_TYPE_STRING                    16
#define TOKEN_TYPE_BLOB                      17
#define TOKEN_SELECT                         18
#define TOKEN_PROJECT                        19
#define TOKEN_MEAN                           20
#define TOKEN_SUM                            21
#define TOKEN_ELECT                          22
#define TOKEN_RECENT                         23
#define TOKEN_SLIDE                          24
#define TOKEN_INTEGER                        25
#define TOKEN_FLOAT                          26
#define TOKEN_ROWS                           27
#define TOKEN_MSEC                           28
#define TOKEN_SEC                            29
#define TOKEN_MIN                            30
#define TOKEN_HOUR                           31
#define TOKEN_DAY                            32
#define TOKEN_DOT                            33
#define TOKEN_NOT                            34
#define TOKEN_STRING                         35
#define TOKEN_BLOB                           36
#define TOKEN_AND                            37
#define TOKEN_OR                             38
#define TOKEN_EQUAL                          39
#define TOKEN_NOT_EQUAL                      40
#define TOKEN_LESS_THAN                      41
#define TOKEN_LESS_THAN_EQUAL                42
#define TOKEN_GREATER_THAN                   43
#define TOKEN_GREATER_THAN_EQUAL             44
