# -*- python -*-

subdirs = "ast tools"

def options(opt):
    opt.recurse(subdirs)

def configure(conf):
    conf.recurse(subdirs)

def build(bld):
    bld.program(
      source   = "parser.c",
      target   = "parser",
      includes = ". ../../"
    )
    bld.recurse(subdirs)
