# -*- python -*-

subdirs = ""

def options(opt):
    opt.recurse(subdirs)

def configure(conf):
    conf.recurse(subdirs)

def build(bld):
    def do_test(name):
        bld.program(
            features = 'testt',
            source   = name + '.cpp',
            includes = '../../src',
            target   = name,
            uselib   = 'GTEST_MAIN',
            use      = "visitor"
        )
    do_test("test_ast_visitor")
    do_test("test_lexer")
    do_test("test_lexer_cpl")
    do_test("test_ddl_parser")
    do_test("test_condition_parser")
    bld.recurse(subdirs)
