# -*- python -*-

subdirs = ""

def options(opt):
    opt.recurse(subdirs)

def configure(conf):
    conf.recurse(subdirs)

def build(bld):
    bld.program(
        features = 'testt',
        source   = 'test_lexer.cpp',
        includes = '../../src',
        target   = 'test_lexer',
        uselib   = 'GTEST_MAIN'
    )
    bld.recurse(subdirs)
