# -*- python -*-

subdirs = ""

def options(opt):
    opt.recurse(subdirs)

def configure(conf):
    conf.recurse(subdirs)

def build(bld):
    # features = 'pyext',
    # source = "mymodule.cpp",
    # target = "myfoo",
    # use = "PYTHON BOOST_PYTHON")

    # bld.objects(
    #     source   = "visitor.cpp",
    #     target   = "visitor",
    #     includes = ". ../../../"
    # )
    # bld.program(
    #   source   = "visitor.cpp",
    #   target   = "visitor",
    #   includes = ". ../../../"
    # )
    bld.recurse(subdirs)
