# -*- python -*-

subdirs = ""

def options(opt):
    opt.recurse(subdirs)

def configure(conf):
    conf.recurse(subdirs)

def build(bld):
    bld.program(
      source   = "lemon.c",
      target   = "lemon"
    )
    bld.recurse(subdirs)
