# -*- python -*-

subdirs = ""

def options(opt):
    opt.recurse(subdirs)

def configure(conf):
    conf.recurse(subdirs)

def build(bld):
    # bld.program(
    #   source   = "server.cpp",
    #   target   = "currentiaserver",
    #   includes = ". ../../",
    #   lib      = ["pthread"],
    # )

    bld.program(
      source   = "experiment_lock.cpp",
      target   = "experiment_lock",
      includes = ". ../../",
      lib      = ["pthread"],
    )

    bld.program(
      source   = "experiment_scheduling.cpp",
      target   = "experiment_scheduling",
      includes = ". ../../",
      lib      = ["pthread"],
    )

    # bld.program(
    #   source   = "experiment_versioning.cpp",
    #   target   = "experiment_versioning",
    #   includes = ". ../../",
    #   lib      = ["pthread"],
    # )

    bld.recurse(subdirs)
