# -*- python -*-

subdirs = ""

def options(opt):
    opt.recurse(subdirs)

def configure(conf):
    conf.recurse(subdirs)

def build(bld):
    bld.program(
      source   = "server.cpp",
      target   = "currentiaserver",
      includes = ". ../../",
      lib      = ["pthread"],
    )

    bld.recurse(subdirs)
